//
//  AppConstants.h
//  IosApplicationFrameworkProject
//
//  Created by Ranjit singh on 2/9/15.
//  Copyright (c) 2015 syslogic. All rights reserved.
//

#ifndef __APP_CONSTANTS_H__
#define __APP_CONSTANTS_H__

#import <Foundation/Foundation.h>

// start View Factory Constant here

typedef enum ViewFactoryScreen
{
    VF_ROOT_VIEW_SCREEN,
    VF_JOB_LIST_CUSTOM_NAVIGATION_CONTROLLER_SCREEN,
    VF_JOB_LIST_ROOT_CUSTOM_NAVIGATION_CONTROLLER_SCREEN,
    VF_SPLASH_SCREEN,
    VF_LOGIN_SCREEN,
    VF_SIGNUP_SCREEN,
    VF_HOME_SCREEN,
    VF_EQUIPMENT_DETAILS_SCREEN,
    VF_SEARCH_BAR_SCREEN,
    VF_EQUIPMENT_MAP_VIEW_SCREEN,
    VF_EQUIPMENT_RENT_REQUEST_RENTER_VIEW_SCREEN,
    VF_RENTAL_REQUEST_LIST_VIEW_SCREEN,
    VF_RENTAL_REQUEST_INDIVIDUAL_VIEW_SCREEN,
    VF_SUPPLIER_REQUEST_INDIVIDUAL_VIEW_SCREEN,
    VF_DASHBOARD_VIEW_SCREEN,
    VF_INVENTORY_VIEW_SCREEN,
    VF_INDIVIDUAL_REQUEST_VIEW_SCREEN,
    VF_INDIVIDUAL_CONTRACT_VIEW_SCREEN,
    VF_CHAT_VIEW_SCREEN,
    VF_RENTAL_CONTRACT_LIST_VIEW_SCREEN,
    VF_RENTAL_SUPPLIER_INDIVIDUAL_CONTRACT_VIEW_SCREEN,
    
} VF;


typedef enum Events
{
    EVENT_ID_FINISH_SCREEN,
    EVENT_ID_SPLASH_SCREEN,
    EVENT_ID_ON_SCREEN_FINISH,
    EVENT_ID_JOB_LIST_ROOT_CUSTOM_NAVIGATION_CONTROLLER_SCREEN,
    EVENT_ID_FINISH_CHILD_CUSTOM_NAVIGATION_SCREEN,
    EVENT_ID_DESTROY_LOCAL_MODEL,
    
    EVENT_ID_LOGIN_SCREEN,
    EVENT_ID_SIGNUP_SCREEN,
    EVENT_ID_HOME_SCREEN,
    EVENT_ID_EQUIPMENT_DETAILS_SCREEN,
    EVENT_ID_SEARCH_BAR_SCREEN,
    EVENT_ID_EQUIPMENT_MAP_VIEW_SCREEN,
    EVENT_ID_EQUIPMENT_RENT_REQUEST_RENTER_VIEW_SCREEN,
    EVENT_ID_RENTAL_REQUEST_LIST_VIEW_SCREEN,
    EVENT_ID_RENTAL_REQUEST_INDIVIDUAL_VIEW_SCREEN,
    EVENT_ID_SUPPLIER_REQUEST_INDIVIDUAL_VIEW_SCREEN,
    EVENT_ID_DASHBOARD_VIEW_SCREEN,
    EVENT_ID_INVENTORY_VIEW_SCREEN,
    EVENT_ID_INDIVIDUAL_REQUEST_VIEW_SCREEN,
    EVENT_ID_INDIVIDUAL_CONTRACT_VIEW_SCREEN,
    EVENT_ID_CHAT_VIEW_SCREEN,
    EVENT_ID_RENTAL_CONTRACT_LIST_VIEW_SCREEN,
    EVENT_ID_RENTAL_SUPPLIER_INDIVIDUAL_CONTRACT_VIEW_SCREEN,
    
}EventId;

typedef enum ViewControllerType
{
    VCT_VIEW_CONTROLLER,
    VCT_ROOT_NAVIGATION_CONTROLLER,
    VCT_CHILD_NAVIGATION_CONTROLLER,
    VCT_ROOT_CUSTOM_NAVIGATION_CONTROLLER,
    VCT_CHILD_CUSTOM_NAVIGATION_CONTROLLER,
    
}VCT;
// end view factory constatn here

extern NSString* const SERVER_URL;
extern NSString* const URL_GET_EQUIPMENT_LIST;
extern NSString* const URL_POST_REGISTRATION;
extern NSInteger const DEFAULT_ORDER_STATUS;
extern NSString *const URL_POST_LOGIN;
extern NSString *const URL_GET_FILTER_CATEGORIES;
extern NSString *const URL_GET_ALL_SEARCH_DATA;
extern NSString *const URL_GET_ALL_SEARCH_TEXT_RELATED_DATA;
extern NSString *const URL_GET_INDIVIDUAL_EQUIPMENT_DETAILS;
extern NSString *const URL_GET_OTHER_RELATED_EQUIPMENT_DETAILS;
extern NSString *const URL_POST_RENTAL_REQUEST ;
extern NSString *const URL_GET_RENTAL_REQUEST_LIST;
extern NSString *const URL_GET_RENTER_INVENTORY;
extern NSString *const URL_GET_SUPPLIER_REQUEST_LIST;
extern NSString *const URL_GET_SUPPLIER_INVENTORY;
extern NSString *const URL_GET_RENTER_CONTRACT_RENT_EQUIPMENT;
extern NSString *const URL_GET_RENTER_CONTRACT_SOLD_EQUIPMENT;
extern NSString *const URL_GET_SUPPLIER_CONTRACT_RENT_EQUIPMENT ;
extern NSString *const URL_GET_SUPPLIER_CONTRACT_SOLD_EQUIPMENT;
extern NSString *const URL_GET_RENTER_INDIVIDUAL_CONTRACT_RENT_EQUIPMENT;
extern NSString *const URL_GET_RENTER_INDIVIDUAL_CONTRACT_SOLD_EQUIPMENT;
extern NSString *const URL_GET_SUPPLIER_INDIVIDUAL_CONTRACT_RENT_EQUIPMENT;
extern NSString *const URL_GET_SUPPLIER_INDIVIDUAL_CONTRACT_SOLD_EQUIPMENT;
extern NSString *const URL_POST_SUPPLIER_REQUEST_APPROVAL;


extern NSString* const CUSTOM_ALERT_ERROR_TITLE;
extern NSString* const CUSTOM_ALERT_PROGRESS_TITLE;
extern NSString* const MANDATORY_FIELD_ERROR_MESSAGE;
extern NSString* const INCORRECT_EMAIL_ERROR_MESSAGE;
extern NSString* const INCORRECT_PHONE_NUMBER_ERROR_MESSAGE;
extern NSString* const CONFIRM_PASSWORD_ERROR_MESSAGE;
extern NSString* const PASSWORD_LENGTH_ERROR_MESSAGE;
extern NSString* const USERNAME_LENGTH_ERROR_MESSAGE;
extern NSString* const CUSTOM_ALERT_PROGRESS_SEARCH;
extern NSString* const IMAGE_REQUEST_FROM_EQUIPMENT_INDIVIDUAL_MODEL;
extern NSString* const IMAGE_REQUEST_FROM_OTHER_EQUIPMENT_MODEL;
extern NSString* const IMAGE_REQUEST_FROM_INVENTORY_MODEL;
extern NSString* const IMAGE_REQUEST_FROM_INDIVIDUAL_CONTRACT;
extern NSString* const LOGIN_TYPE_SUPPLIER;
extern NSString* const IMAGE_REQUEST_FROM_RENT;
extern NSString* const IMAGE_REQUEST_FROM_SOLD;
extern NSString* const IMAGE_REQUEST_FROM_IDLE;
extern NSString* const RENTER_CONTRACT_RENT_REQUEST;
extern NSString* const RENTER_CONTRACT_PURCHASE_REQUEST;
extern NSString * const IMAGE_DOWNLOAD_REQUEST_FOR_RENTER;
extern NSString * const IMAGE_DOWNLOAD_REQUEST_FOR_SUPPLIER;


extern int const SUCCESS_CODE ;
extern int const SPLASH_SCREEN_DISPLAY_LENGTH;


#define APP_THEME_BLUE_COLOR @"3074AE"

#define ReceiverCellIndex 0



@interface AppConstants : NSObject



@end

#endif